
# Create a Python list of at least 50 (lowercase, but including spaces) keywords
# with all the ways Democrats call Republicans on Reddit. Use any terms which
# can be used neutrally, pejoratively, or respectfully. Try to avoid false
# positives like "red".
REPUBLICAN_KEYWORDS = [
    "gop",
    "conservatives",
    "right-wingers",
    "republicans",
    "right-leaning",
    "elephants",
    "righties",
    "rightists",
    "red states",
    "the grand old party",
    "rinos",
    "neocons",
    "tea partiers",
    "trumpists",
    "trump supporters",
    "right-wing extremists",
    "reactionaries",
    "right-wing populists",
    "authoritarians",
    "the religious right",
    "the conservative base",
    "the establishment",
    "the right-wing media",
    "the alt-right",
    "fox news viewers",
    "the koch brothers",
    "climate change deniers",
    "corporate interests",
    "wall street republicans",
    "war hawks",
    "pro-life advocates",
    "gun rights advocates",
    "states' rights supporters",
    "small government proponents",
    "fiscal conservatives",
    "free market enthusiasts",
    "traditionalists",
    "nationalists",
    "anti-abortion activists",
    "gun enthusiasts",
    "big tent coalition",
    "mainstream conservatives",
    "moderates",
    "conservative intellectuals",
    "libertarians",
    "never-Trumpers",
    "centrists",
    "conservative politicians",
    "republican lawmakers",
    "right-wing candidates",
    "gop supporters",
    "red state voters",
    "conservative voters",
    "conservative activists",
    "republican strategists",
]

# Create a Python list of at least 50 (lowercase, but including spaces) keywords
# with all the ways Republicans call Democrats on Reddit. Use any terms which
# can be used neutrally, pejoratively, or respectfully. Try to avoid false
# positives like "blue".

DEMOCRACT_KEYWORDS = [
    "dems",
    "liberals",
    "left-wingers",
    "democrats",
    "progressives",
    "blue team",
    "blue states",
    "democratic party",
    "lefties",
    "liberal base",
    "establishment",
    "left-wing media",
    "radical left",
    "woke left",
    "socialists",
    "identity politics",
    "big government advocates",
    "tax-and-spend",
    "bleeding heart liberals",
    "snowflakes",
    "coastal elite",
    "hollywood liberals",
    "latte liberals",
    "limousine liberals",
    "globalists",
    "radical activists",
    "far left",
    "socialist agenda",
    "nanny state",
    "tree huggers",
    "job killers",
    "cancel culture",
    "political correctness",
    "liberal media bias",
    "tax raisers",
    "handout seekers",
    "social justice warriors",
    "gun control advocates",
    "open borders supporters",
    "big tech sympathizers",
    "wealth redistribution",
    "identity politics",
    "deep state",
    "liberal politicians",
    "Democratic lawmakers",
    "left-wing candidates",
    "progressive activists",
    "blue wave",
    "democratic voters",
    "liberal elites",
    "leftist policies",
    "left-leaning intellectuals",
]
