
# Create a Python list of at least 50 (lowercase, but including spaces) keywords
# with all the ways Democrats call Republicans on Reddit. Use any terms which
# can be used neutrally, pejoratively, or respectfully. Try to avoid false
# positives like "red".
REPUBLICAN_KEYWORDS = [
    "gop",
    "conservatives",
    "conservative voters",
    "conservative party",
    "right wing",
    "republicans",
    "right leaning",
    "elephants",
    "righties",
    "rightists",
    "right leaning",
    "red states",
    "red party",
    "grand old party",
    "rinos",
    "fascists",
    "neoconservatives",
    "tea partiers",
    "trumpists",
    "reactionaries",
    "authoritarians",
    "religious right",
    "alt right",
    "fox news viewers",
    "climate change deniers",
    "war hawks",
    "pro life advocates",
    "gun rights advocates",
    "small government proponents",
    "free market enthusiasts",
    "traditionalists",
    "nationalists",
    "anti abortion activists",
    "gun enthusiasts",
    "big tent coalition",
    "gop supporters",
    "red state voters",
    # politicians
    "koch brothers",
    "trump",
    "donald",
    "pence",
    "mitch mcconnell",
    "lindsey graham",
    "ted cruz",
    "marco rubio",
    "rand paul",
    "mike pompeo",
    "mike huckabee",
    "rick santorum",
    "rick perry",
    "rick scott",
    "jeb bush",
    "john kasich",
    "chris christie",
    "bobby jindal",
    "scott walker",
    "john bolton",
    "ben carson",
    "carly fiorina",
    "sarah palin",
]

# Create a Python list of at least 50 (lowercase, but including spaces) keywords
# with all the ways Republicans call Democrats on Reddit. Use any terms which
# can be used neutrally, pejoratively, or respectfully. Try to avoid false
# positives like "blue".

DEMOCRACT_KEYWORDS = [
    "liberals",
    "left wing",
    "democrats",
    "democratic voters",
    "democratic party",
    "communists",
    "progressives",
    "blue party",
    "blue team",
    "blue states",
    "lefties",
    "leftists",
    "radical left",
    "far left",
    "left leaning",
    "woke",
    "big government advocates",
    "tax and spend",
    "snowflakes",
    "socialists",
    "tree huggers",
    "job killers",
    "tax raisers",
    "social justice warriors",
    "gun control advocates",
    "open borders supporters",
    "wealth redistribution",
    "progressive",
    "blue wave",
    # politicians
    "biden",
    "kamala harris",
    "bernie",
    "sanders",
    "elizabeth warren",
    "amy klobuchar",
    "pete buttigieg",
    "andrew yang",
    "cory booker",
    "julian castro",
    "kirsten gillibrand",
    "tulsi gabbard",
    "jay inslee",
    "john delaney",
    "obama",
    "hillary",
    "clinton",
    "nancy pelosi",
    "chuck schumer",
    "alexandria ocasio cortez",
]
