
# Create a Python list of at least 50 (lowercase, but including spaces) keywords
# with all the ways Democrats call Republicans on Reddit. Use any terms which
# can be used neutrally, pejoratively, or respectfully. Try to avoid false
# positives like "red".
REPUBLICAN_KEYWORDS = [
    "gop",
    "conservatives",
    "right wing",
    "republicans",
    "right leaning",
    "elephants",
    "righties",
    "rightists",
    "red states",
    "grand old party",
    "rinos",
    "neocons",
    "tea partiers",
    "trumpists",
    "reactionaries",
    "authoritarians",
    "religious right",
    "alt right",
    "fox news viewers",
    "koch brothers",
    "climate change deniers",
    "war hawks",
    "pro life advocates",
    "gun rights advocates",
    "small government proponents",
    "free market enthusiasts",
    "traditionalists",
    "nationalists",
    "anti abortion activists",
    "gun enthusiasts",
    "big tent coalition",
    "republican lawmakers",
    "gop supporters",
    "red state voters",
    # politicians
    "trump",
    "mike pence",
    "mitch mcconnell",
    "lindsey graham",
    "ted cruz",
    "marco rubio",
    "rand paul",
    "mike pompeo",
    "mike huckabee",
    "rick santorum",
    "rick perry",
    "rick scott",
    "jeb bush",
    "john kasich",
    "chris christie",
    "bobby jindal",
    "scott walker",
    "john bolton",
    "ben carson",
    "carly fiorina",
    "sarah palin",
]

# Create a Python list of at least 50 (lowercase, but including spaces) keywords
# with all the ways Republicans call Democrats on Reddit. Use any terms which
# can be used neutrally, pejoratively, or respectfully. Try to avoid false
# positives like "blue".

DEMOCRACT_KEYWORDS = [
    "liberals",
    "left wing",
    "democrats",
    "progressives",
    "blue team",
    "blue states",
    "democratic party",
    "lefties",
    "leftists",
    "radical left",
    "woke",
    "socialists",
    "identity politics",
    "big government advocates",
    "tax and spend",
    "snowflakes",
    "coastal elite",
    "globalists",
    "radical activists",
    "far left",
    "socialist agenda",
    "nanny state",
    "tree huggers",
    "job killers",
    "cancel culture",
    "political correctness",
    "liberal media",
    "tax raisers",
    "social justice warriors",
    "gun control advocates",
    "open borders supporters",
    "wealth redistribution",
    "liberal politicians",
    "progressive",
    "blue wave",
    "democratic voters",
    "liberal elites",
    "left leaning",
    # politicians
    "biden",
    "kamala harris",
    "bernie sanders",
    "elizabeth warren",
    "amy klobuchar",
    "pete buttigieg",
    "andrew yang",
    "cory booker",
    "julian castro",
    "kirsten gillibrand",
    "tulsi gabbard",
    "jay inslee",
    "john delaney",
    "obama",
    "bill clinton",
    "hillary clinton",
    "nancy pelosi",
    "chuck schumer",
    "alexandria ocasio cortez",
]
